DATA SEGMENT
    S1 DB 10 DUP('?')
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    MOV SI,OFFSET S1
    MOV CX,10
    MOV AH,01H
L1: INT 21H
    MOV [SI],AL
    INC SI
    LOOP L1
    MOV AH,2
    MOV DL,0DH
    INT 21H
    MOV DL,0AH
    INT 21H
    MOV CX,9
L2: MOV BX,CX
    MOV SI,0
L3: MOV AL,S1[SI]
    CMP S1[SI+1],AL
    JGE L4
    XCHG S1[SI+1],AL
    MOV S1[SI],AL
L4: INC SI
    LOOP L3
    MOV CX,BX
    LOOP L2
    MOV CX,10
    MOV SI,0
    MOV AH,02
L5: MOV DL,S1[SI]
    INT 21H
    INC SI
    LOOP L5
    MOV AH,4CH
    INT 21H
CODE ENDS
    END START