DATA SEGMENT
    HW DB 'Hello world',13,10,'$'
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    MOV DX,OFFSET HW
    MOV AH,9
    INT 21H
    MOV AH,4CH
    INT 21H
CODE ENDS
    END START